# Generated by Django 2.0.4 on 2018-04-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('token', models.AutoField(primary_key=True, serialize=False)),
                ('gameboard', models.CharField(max_length=64)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
