# Generated by Django 2.0.4 on 2018-04-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameboard',
            field=models.CharField(default='0000000000000000000000000001200000021000000000000000000000000000', max_length=64),
        ),
    ]
