# Generated by Django 2.0.4 on 2018-04-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180409_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timer',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=2),
        ),
    ]
