# Generated by Django 2.0.4 on 2018-04-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180410_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameEnd',
            field=models.IntegerField(default=0),
        ),
    ]
